env:

appName: reviews-parsing-mlsys

gcpProjectName:

emailForCertIssuer:

# Use staging for development to avoid rate limit. Once done can switch to prod.
# letsencryptIssuer: letsencrypt-staging
letsencryptIssuer: letsencrypt-prod

namespaces:
  - default
  - monitoring
  - cicd

# Below is to configure Nginx IP Whitelisting to work with GKE Inherent Traffic Routing
ingress:
  whitelistIpsAnnotations:
  whitelistIPs:
    - "<IP_ADDRESS>/32"
