services:
  mlserver:
    container_name: mlserver
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - ../../.env.staging

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.59
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "6831:6831"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
