services:
  mlserver:
    container_name: mlserver
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - ../../.env.staging

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.59
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      # Below is to enable connection from all host so that mlserver can connect
      - COLLECTOR_OTLP_HTTP_HOST_PORT=:4318
